### ISSUE TITLE
Redis 2.6 supports MIGRATE

### ISSUE THREAD

**Issue by OriPekelman** [yankov/redis-migrator#1]
Probably too early as long as 2.6 is in RC. So this is a place holder issue.
Redis 2.6 supports the MIGRATE command that allows to atomically migrate a key between two servers without the need to know the type of the key.
from the docs:

```
Atomically transfer a key from a source Redis instance to a destination Redis instance. On success the key is deleted from the original instance and is guaranteed to exist in the target instance.
```

Usage :

```
MIGRATE host port key destination-db timeout
```

**Comment by yankov** [comment]
Solved here https://github.com/yankov/redis-migrator/pull/4
